import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { login } from '../common/auth';
import Button from '../components/button';
import TextInput from '../components/text-input';

type Props = {};

const LoginPage = (props: Props) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const router = useRouter();

  // const handleLoginInfoChange = (event: React.FormEvent<HTMLInputElement>) => {
  //   const id = event.currentTarget?.id;
  //   const value = event.currentTarget?.value;

  //   if (id === 'inputEmail') {
  //     setEmail(value);
  //   } else if (id === 'inputPassword') {
  //     setPassword(value);
  //   }
  // };

  const handleEmailChange = (event: React.FormEvent<HTMLInputElement>) => {
    setEmail(event.currentTarget?.value);
  };

  const handlePasswordChange = (event: React.FormEvent<HTMLInputElement>) => {
    setPassword(event.currentTarget?.value);
  };

  const handleClickLogin = () => {
    login(
      email,
      password,
      () => {
        router.push('/chat');
      },
      (error: any) => {
        console.error(error.code);
        setError('Invalid email/password');
      }
    );
  };

  return (
    <>
      <Head>
        <title>Ask Tim Ferris - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl">Login</h1>
        <TextInput placeholder="Email" value={email} changeHandler={handleEmailChange} />
        <TextInput
          placeholder="Password"
          value={password}
          changeHandler={handlePasswordChange}
          password={true}
        />
        <Button clickHandler={handleClickLogin} text="Login" />
        <Button isLink={true} href="/register" text="Register" />
        {error ? <p>{error}</p> : null}
      </main>
    </>
  );
};

export default LoginPage;
