import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { register } from '../common/auth';
import Button from '../components/button';

type Props = {};

const RegisterPage = (props: Props) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const router = useRouter();

  const handleRegisterInfoChange = (event: React.FormEvent<HTMLInputElement>) => {
    const id = event.currentTarget?.id;
    const value = event.currentTarget?.value;

    if (id === 'inputName') {
      setName(value);
    } else if (id === 'inputEmail') {
      setEmail(value);
    } else if (id === 'inputPassword') {
      setPassword(value);
    }
  };

  const handleRegisterClick = async () => {
    register(
      email,
      password,
      name,
      () => {
        router.push('/login');
      },
      (error: any) => {
        console.log(error.code);
        console.log(error.message);

        if (error.code === 'auth/email-already-in-use') {
          setError('Email already in use. Try logging in?');
        }
      }
    );
  };

  return (
    <>
      <Head>
        <title>Ask Tim Ferris - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl">Register</h1>
        <input type="text" placeholder="Name" id="inputName" onChange={handleRegisterInfoChange} />
        <input
          type="text"
          placeholder="Email"
          id="inputEmail"
          onChange={handleRegisterInfoChange}
        />
        <input
          type="password"
          placeholder="Password"
          id="inputPassword"
          onChange={handleRegisterInfoChange}
        />
        <Button text="Register" clickHandler={handleRegisterClick} />
        <Button isLink={true} href="/login" text="Login" />
        {error ? <p>{error}</p> : null}
      </main>
    </>
  );
};

export default RegisterPage;
