import Head from 'next/head';
import React from 'react';

type Props = {};

const LoginPage = (props: Props) => {
  return (
    <>
      <Head>
        <title>Ask Tim Ferris - Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl">Chat Page</h1>
      </main>
    </>
  );
};

export default LoginPage;
